### ISSUE TITLE
Allow `unlink` and `unlinkat` for `builtin::SystemIO` 

### ISSUE THREAD

**Issue by gotlougit** [boustrophedon/extrasafe#17]
Right now, it isn't possible to use `extrasafe` to restrict syscalls for any operations involving an SQLite database, since a journal file needs to be deleted. While deleting is a somewhat sensitive operation, I think it'd be nice to have an option in the builtin `SystemIO` rule set to allow this syscall.

I will try and and create a suitable patch that we can merge for this, but feel free to suggest alternative ideas for this.

**Comment by boustrophedon** [comment]
Hi, thanks for the issue!

I'd be glad to accept a patch for a method on SystemIO that allows unlink/unlinkat, `allow_unlink` or something, but I'm also currently working on switching extrasafe to use seccompiler instead of libseccomp. I also have some commits I haven't published yet but I'll try and push them today so you don't have to rebase.

**Comment by gotlougit** [comment]
Sure!

**Comment by boustrophedon** [comment]
I've landed #18 which has the cleanups I mentioned. If you want to create a PR for `SystemIO::allow_unlink` or similar I'd be glad to review it.
