### ISSUE TITLE
pipe() syscall isn't covered by extrasafe

### ISSUE THREAD

**Issue by gotlougit** [boustrophedon/extrasafe#22]
Hello again, I've been continuing work on my [sshield](https://github.com/gotlougit/sshield) program and have run into more issues with using `extrasafe`. More specifically, now `pipe()` or `pipe2()` syscalls aren't covered by `extrasafe`.

I think the ideal place for these to exist would be `builtins::danger_zone`, though I am not sure, thus creating this issue. I'd be happy to create a PR to get this functionality in the code.

**Comment by boustrophedon** [comment]
Hi!

I think it's a good idea, but in the meantime you can always implement your own RuleSet and include whatever syscalls you'd like, see the user guide code here: https://github.com/boustrophedon/extrasafe/blob/master/examples/user-guide.rs#L24

I probably should add something in tests/ as well or make it more obvious.

Either way, adding pipes to an existing ruleset, probably threads or forkandexec, is a good idea. I don't think creating pipes are particularly dangerous since you still need read/write to use them.
